name: Label Issues (Permissions Example)

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  contents: read

jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name: Debug issue information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Issue number: ${{ github.event.issue.number }}"
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Contains 'bug': ${{ contains(github.event.issue.title, 'bug') }}"
      
      - name: Create bug label if it doesn't exist
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
            --url "https://api.github.com/repos/${{ github.repository }}/labels" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"name": "bug", "color": "d73a4a", "description": "Something is not working"}' \
            --silent --fail || echo "Label might already exist, continuing..."
      
      - name: Assign label if title contains "bug"
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST \
            --url "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -d '{"labels": ["bug"]}' \
            --fail
